"use client";
import { motion } from "framer-motion";
import Navbar from "../components/Navbar";

const SAMPLE_DATASETS = [
  { id: 1, name: "Malaria Patient Records — Kano State", domain: "healthcare", country: "Nigeria", flag: "🇳🇬", rows: 50000, format: "CSV", created: "2 hours ago", tags: ["malaria", "patient-records", "public-health"] },
  { id: 2, name: "M-Pesa Transaction Data — Nairobi", domain: "finance", country: "Kenya", flag: "🇰🇪", rows: 100000, format: "JSON", created: "5 hours ago", tags: ["mobile-money", "transactions", "fintech"] },
  { id: 3, name: "Maize Yield Records — Zambia 2024", domain: "agriculture", country: "Zambia", flag: "🇿🇲", rows: 10000, format: "CSV", created: "1 day ago", tags: ["maize", "crop-yield", "farming"] },
  { id: 4, name: "Diabetes Patient Data — Accra", domain: "healthcare", country: "Ghana", flag: "🇬🇭", rows: 25000, format: "CSV", created: "1 day ago", tags: ["diabetes", "chronic-disease", "hospital"] },
  { id: 5, name: "Mobile Money Fraud Cases — Lagos", domain: "finance", country: "Nigeria", flag: "🇳🇬", rows: 15000, format: "JSONL", created: "2 days ago", tags: ["fraud", "mobile-banking", "security"] },
  { id: 6, name: "Coffee Farm Data — Ethiopia", domain: "agriculture", country: "Ethiopia", flag: "🇪🇹", rows: 8000, format: "CSV", created: "2 days ago", tags: ["coffee", "export", "smallholder-farms"] },
  { id: 7, name: "HIV/AIDS Patient Records — Johannesburg", domain: "healthcare", country: "South Africa", flag: "🇿🇦", rows: 30000, format: "CSV", created: "3 days ago", tags: ["HIV", "AIDS", "ARV-treatment"] },
  { id: 8, name: "Airtime Transfer Records — West Africa", domain: "finance", country: "Ghana", flag: "🇬🇭", rows: 75000, format: "JSON", created: "3 days ago", tags: ["airtime", "telecom", "payments"] },
];

const DOMAIN_COLORS: Record<string, { bg: string; text: string; border: string }> = {
  healthcare: { bg: "#fee2e2", text: "#ef4444", border: "#fca5a5" },
  finance: { bg: "#fef3c7", text: "#d97706", border: "#fcd34d" },
  agriculture: { bg: "#dcfce7", text: "#16a34a", border: "#86efac" },
};

export default function CatalogPage() {
  return (
    <div style={{ minHeight: "100vh", background: "var(--bg)" }}>
      <Navbar />

      <div style={{ maxWidth: 1200, margin: "0 auto", padding: "40px 24px" }}>
        <motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }}>
          <h1 style={{ fontSize: 28, fontWeight: 700, color: "var(--text)", marginBottom: 6 }}>
            Dataset Catalog
          </h1>
          <p style={{ fontSize: 15, color: "var(--text-muted)", marginBottom: 32 }}>
            Browse synthetic datasets generated by the AfriGen community
          </p>
        </motion.div>

        {/* Filter bar */}
        <motion.div
          initial={{ opacity: 0, y: 10 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ delay: 0.1 }}
          style={{
            display: "flex", gap: 8, marginBottom: 24, flexWrap: "wrap",
          }}
        >
          {["All", "Healthcare", "Finance", "Agriculture"].map(f => (
            <button key={f} style={{
              padding: "6px 16px", borderRadius: 20, fontSize: 13, fontWeight: 500,
              border: "1px solid var(--border)",
              background: f === "All" ? "var(--accent)" : "var(--bg)",
              color: f === "All" ? "white" : "var(--text-muted)",
              cursor: "pointer",
            }}>
              {f}
            </button>
          ))}
          <div style={{ marginLeft: "auto" }}>
            <input
              placeholder="Search datasets..."
              style={{
                padding: "6px 14px", borderRadius: 20,
                border: "1px solid var(--border)", fontSize: 13,
                outline: "none", width: 220, fontFamily: "var(--sans)",
                color: "var(--text)", background: "var(--bg)",
              }}
            />
          </div>
        </motion.div>

        {/* Dataset grid */}
        <div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fill, minmax(340px, 1fr))", gap: 16 }}>
          {SAMPLE_DATASETS.map((dataset, i) => {
            const colors = DOMAIN_COLORS[dataset.domain];
            return (
              <motion.div
                key={dataset.id}
                initial={{ opacity: 0, y: 20 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ delay: i * 0.05 }}
                whileHover={{ y: -2, boxShadow: "var(--shadow-md)" }}
                style={{
                  background: "var(--bg)", border: "1px solid var(--border)",
                  borderRadius: "var(--radius-lg)", padding: 20,
                  cursor: "pointer", transition: "all 0.2s",
                  boxShadow: "var(--shadow-sm)",
                }}
              >
                <div style={{ display: "flex", alignItems: "flex-start", justifyContent: "space-between", marginBottom: 12 }}>
                  <span style={{
                    fontSize: 11, fontWeight: 600,
                    color: colors.text, background: colors.bg,
                    border: `1px solid ${colors.border}`,
                    padding: "2px 8px", borderRadius: 20,
                    textTransform: "uppercase", letterSpacing: "0.05em",
                  }}>
                    {dataset.domain}
                  </span>
                  <span style={{ fontSize: 13 }}>{dataset.flag}</span>
                </div>

                <div style={{ fontSize: 14, fontWeight: 600, color: "var(--text)", marginBottom: 4, lineHeight: 1.4 }}>
                  {dataset.name}
                </div>
                <div style={{ fontSize: 12, color: "var(--text-dim)", marginBottom: 14 }}>
                  {dataset.country} · {dataset.rows.toLocaleString()} rows · {dataset.format}
                </div>

                <div style={{ display: "flex", flexWrap: "wrap", gap: 4, marginBottom: 14 }}>
                  {dataset.tags.map(tag => (
                    <span key={tag} style={{
                      fontSize: 11, color: "var(--text-dim)",
                      background: "var(--bg-tertiary)",
                      border: "1px solid var(--border)",
                      padding: "2px 8px", borderRadius: 4,
                    }}>
                      #{tag}
                    </span>
                  ))}
                </div>

                <div style={{ display: "flex", alignItems: "center", justifyContent: "space-between" }}>
                  <span style={{ fontSize: 11, color: "var(--text-dim)" }}>{dataset.created}</span>
                  <button style={{
                    fontSize: 12, fontWeight: 500, color: "var(--accent2)",
                    background: "var(--accent2-light)", border: "none",
                    padding: "4px 12px", borderRadius: 6, cursor: "pointer",
                  }}>
                    Preview →
                  </button>
                </div>
              </motion.div>
            );
          })}
        </div>
      </div>
    </div>
  );
}
